apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
  labels:
    k8slens-edit-resource-version: v1alpha1
  name: kargo-demo
  namespace: argocd
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - stage: test
                - stage: uat
                - stage: prod

          - clusters: {}
              # selector:
              #   matchLabels:
              #     argocd.argoproj.io/secret-type: cluster

  template:
    metadata:
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{stage}}
      name: kargo-demo-{{stage}}-{{name}}
    spec:
      destination:
        namespace: kargo-demo-{{stage}}
        server: '{{server}}'
      project: default
      source:
        path: .
        repoURL: https://github.com/kagodarog/kargo-demo.git
        targetRevision: stage/{{stage}}
      syncPolicy:
        automated:
          allowEmpty: false
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true